version: '3.9'

services:
  db:
    image: postgres
    ports: 
      - 42069:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: "bewise_get_questions"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bewise_get_questions"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G 
    volumes:
      - bewise:/var/lib/postgresql/data

volumes:
  bewise:
    driver: local
