version: '3.9'

services:
  db:
    container_name: postgres_container
    image: postgres
    ports: 
      - 42069:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: "bewise_get_questions"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bewise_get_questions"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G 
    volumes:
      - bewise:/var/lib/postgresql/data
    networks:
        - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@bee.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports: 
      - 42070:80
    restart: unless-stopped
    networks:
        - postgres
volumes:
  bewise:
  pgadmin-data:

networks:
  postgres:
    driver: bridge

